import { normalizeCityName } from './normalizeCityName';

export const citiesAndelys = [
  'Ailly',
  'Alizay',
  'Amécourt',
  'Amfreville-les-Champs',
  'Amfreville-sous-les-Monts',
  'Aubevoye',
  'Autheuil-Authouillet',
  'Authevernes',
  'Bacqueville',
  'Bazincourt-sur-Epte',
  'Beauficel-en-Lyons',
  'Bernières-sur-Seine',
  'Bernouville',
  'Berthenonville',
  'Bézu-la-Forêt',
  'Bézu-Saint-Éloi',
  'Bois-Jérôme-Saint-Ouen',
  'Boisemont',
  'Bosquentin',
  'Bouafles',
  'Bouchevilliers',
  'Bourg-Beaudouin',
  'Bus-Saint-Rémy',
  'Cahaignes',
  'Cailly-sur-Eure',
  'Cantiers',
  'Champenard',
  'Charleval',
  'Château-sur-Epte',
  'Chauvincourt-Provemont',
  'Civières',
  'Corny',
  'Coudray',
  'Courcelles-sur-Seine',
  'Criquebeuf-sur-Seine',
  'Cuverville',
  'Dampsmesnil',
  'Dangu',
  'Daubeuf-près-Vatteville',
  'Doudeauville-en-Vexin',
  'Douville-sur-Andelle',
  'Écardenville-sur-Eure',
  'Écos',
  'Écouis',
  'Étrépagny',
  'Farceaux',
  'Fleury-la-Forêt',
  'Fleury-sur-Andelle',
  'Flipou',
  'Fontaine-Bellenger',
  'Fontaine-Heudebourg',
  'Fontenay',
  'Forêt-la-Folie',
  'Fourges',
  'Fours-en-Vexin',
  'Fresne-l’Archevêque',
  'Gaillardbois-Cressenville',
  'Gaillon',
  'Gamaches-en-Vexin',
  'Gasny',
  'Gisors',
  'Giverny',
  'Grainville',
  'Guerny',
  'Guiseniers',
  'Guitry',
  'Hacqueville',
  'Harquency',
  'Hébécourt',
  'Hennezis',
  'Heubécourt-Haricourt',
  'Heudicourt',
  'Heudreville-sur-Eure',
  'Heuqueville',
  'Houville-en-Vexin',
  'Igoville',
  'La Croix-Saint-Leufroy',
  'La Neuve-Grange',
  'La Roquette',
  'Le Manoir',
  'Le Thil',
  'Le Thuit',
  'Le Tronquay',
  'Léry',
  'Les Andelys',
  'Les Damps',
  'Les Hogues',
  'Les Thilliers-en-Vexin',
  'Letteguives',
  'Lilly',
  'Lisors',
  'Longchamps',
  'Lorleau',
  'Lyons-la-Forêt',
  'Mainneville',
  'Martagny',
  'Martot',
  'Ménesqueville',
  'Mesnil-sous-Vienne',
  'Mesnil-Verclives',
  'Mézières-en-Vexin',
  'Montaure',
  'Morgny',
  'Mouflaines',
  'Muids',
  'Neaufles-Saint-Martin',
  'Nojeon-en-Vexin',
  'Notre-Dame-de-l’Isle',
  'Notre-Dame-du-Vaudreuil',
  'Noyers',
  'Panilleuse',
  'Perriers-sur-Andelle',
  'Perruel',
  'Pîtres',
  'Pont-de-l’Arche',
  'Pont-Saint-Pierre',
  'Port-Mort',
  'Porte-Joie',
  'Poses',
  'Pressagny-l’Orgueilleux',
  'Puchay',
  'Radepont',
  'Renneville',
  'Richeville',
  'Romilly-sur-Andelle',
  'Rosay-sur-Lieure',
  'Saint-Aubin-sur-Gaillon',
  'Saint-Cyr-du-Vaudreuil et Tournedos-sur-Seine',
  'Saint-Denis-le-Ferment',
  'Saint-Étienne-sous-Bailleul',
  'Saint-Julien-de-la-Liègue',
  'Saint-Pierre-de-Bailleul',
  'Saint-Pierre-la-Garenne',
  'Sainte-Barbe-sur-Gaillon',
  'Sainte-Geneviève-lès-Gasny',
  'Sainte-Marie-de-Vatimesnil',
  'Sancourt',
  'Saussay-la-Campagne',
  'Suzay',
  'Tilly',
  'Tosny',
  'Tostes',
  'Touffreville',
  'Tourny',
  'Vandrimare',
  'Vascœuil',
  'Vatteville',
  'Venables',
  'Vesly',
  'Vézillon',
  'Vieux-Villez',
  'Villers-en-Vexin',
  'Villers-sur-le-Roule',
].map(normalizeCityName);
