import { normalizeCityName } from './normalizeCityName';

export const citiesBernay = [
  'Aclou',
  'Ajou',
  'Barc',
  'Barquet',
  'Barville',
  'Bazoques',
  'Beaumesnil',
  'Beaumont-le-Roger',
  'Beaumontel',
  'Bernay',
  'Berthouville',
  'Berville-la-Campagne',
  'Boisney',
  'Boissy-Lamberville',
  'Bosc-Renoult-en-Ouche',
  'Bosrobert',
  'Bournainville-Faverolles',
  'Bray',
  'Brétigny',
  'Brionne',
  'Broglie',
  'Calleville',
  'Caorches-Saint-Nicolas',
  'Capelle-les-Grands',
  'Carsix',
  'Chamblac',
  'Combon',
  'Corneville-la-Fouquetière',
  'Courbépine',
  'Drucourt',
  'Duranville',
  'Écardenville-la-Campagne',
  'Épinay',
  'Ferrières-Saint-Hilaire',
  'Folleville',
  'Fontaine-l’Abbé',
  'Fontaine-la-Louvet',
  'Fontaine-la-Soret',
  'Franqueville',
  'Gisay-la-Coudre',
  'Giverville',
  'Goupillières',
  'Gouttières',
  'Grand-Camp',
  'Grandchain',
  'Grosley-sur-Risle',
  'Harcourt',
  'Hecmanville',
  'Heudreville-en-Lieuvin',
  'La Barre-en-Ouche',
  'La Chapelle-Gauthier',
  'La Chapelle-Hareng',
  'La Goulafrière',
  'La Haye-de-Calleville',
  'La Houssaye',
  'La Neuville-du-Bosc',
  'La Roussière',
  'La Trinité-de-Réville',
  'Landepéreuse',
  'Launay',
  'Le Bec-Hellouin',
  'Le Favril',
  'Le Noyer-en-Ouche',
  'Le Planquay',
  'Le Plessis-Sainte-Opportune',
  'Le Theil-Nolent',
  'Le Tilleul-Othon',
  'Les Jonquerets-de-Livet',
  'Les Places',
  'Livet-sur-Authou',
  'Malleville-sur-le-Bec',
  'Malouy',
  'Mélicourt',
  'Menneval',
  'Mesnil-Rousset',
  'Montreuil-l’Argillé',
  'Morsan',
  'Nassandres',
  'Neuville-sur-Authou',
  'Notre-Dame-d’Épine',
  'Notre-Dame-du-Hamel',
  'Perriers-la-Campagne',
  'Piencourt',
  'Plainville',
  'Plasnes',
  'Romilly-la-Puthenaye',
  'Rouge-Perriers',
  'Saint-Agnan-de-Cernières',
  'Saint-Aubin-de-Scellon',
  'Saint-Aubin-des-Hayes',
  'Saint-Aubin-du-Thenney',
  'Saint-Aubin-le-Guichard',
  'Saint-Aubin-le-Vertueux',
  'Saint-Clair-d’Arcey',
  'Saint-Cyr-de-Salerne',
  'Saint-Denis-d’Augerons',
  'Saint-Éloi-de-Fourques',
  'Saint-Germain-la-Campagne',
  'Saint-Jean-du-Thenney',
  'Saint-Laurent-du-Tencement',
  'Saint-Léger-de-Rôtes',
  'Saint-Mards-de-Fresne',
  'Saint-Martin-du-Tilleul',
  'Saint-Paul-de-Fourques',
  'Saint-Pierre-de-Cernières',
  'Saint-Pierre-de-Salerne',
  'Saint-Pierre-du-Mesnil',
  'Saint-Quentin-des-Isles',
  'Saint-Victor-d’Épine',
  'Saint-Victor-de-Chrétienville',
  'Saint-Vincent-du-Boulay',
  'Sainte-Marguerite-en-Ouche',
  'Sainte-Opportune-du-Bosc',
  'Serquigny',
  'Thevray',
  'Thiberville',
  'Thibouville',
  'Tilleul-Dame-Agnès',
  'Valailles',
  'Verneusses',
].map(normalizeCityName);
