import { normalizeCityName } from './normalizeCityName';

export const citiesLouviers = [
  'Acquigny',
  'Ailly',
  'Alizay',
  'Amfreville-la-Campagne',
  'Amfreville-sur-Iton',
  'Andé',
  'Aubevoye',
  'Autheuil-Authouillet',
  'Bérengeville-la-Campagne',
  'Bernières-sur-Seine',
  'Cailly-sur-Eure',
  'Canappeville',
  'Cesseville',
  'Champenard',
  'Crasville',
  'Crestot',
  'Criquebeuf-la-Campagne',
  'Criquebeuf-sur-Seine',
  'Crosville-la-Vieille',
  'Daubeuf-la-Campagne',
  'Écardenville-sur-Eure',
  'Écauville',
  'Ecquetot',
  'Épégard',
  'Épreville-près-le-Neubourg',
  'Feuguerolles',
  'Fontaine-Bellenger',
  'Fontaine-Heudebourg',
  'Fouqueville',
  'Gaillon',
  'Hectomare',
  'Heudebouville',
  'Heudreville-sur-Eure',
  'Hondouville',
  'Houetteville',
  'Houlbec-près-le-Gros-Theil',
  'Igoville',
  'Incarville',
  'Iville',
  'La Croix-Saint-Leufroy',
  'La Harengère',
  'La Haye-du-Theil',
  'La Haye-le-Comte',
  'La Haye-Malherbe',
  'La Pyle',
  'La Saussaye',
  'La Vacherie',
  'Le Bec-Thomas',
  'Le Gros-Theil',
  'Le Manoir',
  'Le Mesnil-Jourdain',
  'Le Neubourg',
  'Le Thuit-Anger',
  'Le Thuit-Signol',
  'Le Thuit-Simer',
  'Le Tremblay-Omonville',
  'Le Troncq',
  'Léry',
  'Les Damps',
  'Louviers',
  'Mandeville',
  'Marbeuf',
  'Martot',
  'Montaure',
  'Notre-Dame-du-Vaudreuil',
  'Pinterville',
  'Pîtres',
  'Pont-de-l’Arche',
  'Porte-Joie',
  'Poses',
  'Quatremare',
  'Saint-Amand-des-Hautes-Terres',
  'Saint-Aubin-d’Écrosville',
  'Saint-Aubin-sur-Gaillon',
  'Saint-Cyr-du-Vaudreuil et Tournedos-sur-Seine',
  'Saint-Cyr-la-Campagne',
  'Saint-Didier-des-Bois',
  'Saint-Étienne-du-Vauvray',
  'Saint-Étienne-sous-Bailleul',
  'Saint-Germain-de-Pasquier',
  'Saint-Julien-de-la-Liègue',
  'Saint-Meslin-du-Bosc',
  'Saint-Nicolas-du-Bosc',
  'Saint-Ouen-de-Pontcheuil',
  'Saint-Pierre-de-Bailleul',
  'Saint-Pierre-des-Fleurs',
  'Saint-Pierre-du-Bosguérard',
  'Saint-Pierre-du-Vauvray',
  'Saint-Pierre-la-Garenne',
  'Sainte-Barbe-sur-Gaillon',
  'Surtauville',
  'Surville',
  'Tosny',
  'Tostes',
  'Tourville-la-Campagne',
  'Venables',
  'Venon',
  'Vieux-Villez',
  'Villers-sur-le-Roule',
  'Villettes',
  'Villez-sur-le-Neubourg',
  'Vironvay',
  'Vitot',
  'Vraiville',
].map(normalizeCityName);
