import { normalizeCityName } from './normalizeCityName';

export const citiesPontAudemer = [
  'Aizier',
  'Appeville-Annebault',
  'Asnières',
  'Authou',
  'Bailleul-la-Vallée',
  'Barneville-sur-Seine',
  'Berville-en-Roumois',
  'Berville-sur-Mer',
  'Beuzeville',
  'Boissey-le-Châtel',
  'Bonneville-Aptot',
  'Bosc-Bénard-Commin',
  'Bosc-Bénard-Crescy',
  'Bosc-Renoult-en-Roumois',
  'Bosgouet',
  'Bosguérard-de-Marcouville',
  'Bosnormand',
  'Boulleville',
  'Bouquelon',
  'Bouquetot',
  'Bourg-Achard',
  'Bourgtheroulde-Infreville',
  'Bourneville',
  'Brestot',
  'Campigny',
  'Caumont',
  'Cauverville-en-Roumois',
  'Colletot',
  'Condé-sur-Risle',
  'Conteville',
  'Cormeilles',
  'Corneville-sur-Risle',
  'Écaquelon',
  'Épaignes',
  'Épreville-en-Lieuvin',
  'Épreville-en-Roumois',
  'Étréville',
  'Éturqueraye',
  'Fatouville-Grestain',
  'Fiquefleur-Équainville',
  'Flancourt-Catelon',
  'Fort-Moville',
  'Foulbec',
  'Fourmetot',
  'Freneuse-sur-Risle',
  'Fresne-Cauverville',
  'Glos-sur-Risle',
  'Hauville',
  'Honguemare-Guenouville',
  'Illeville-sur-Montfort',
  'La Chapelle-Bayvel',
  'La Haye-Aubrée',
  'La Haye-de-Routot',
  'La Lande-Saint-Léger',
  'La Noë-Poulain',
  'La Poterie-Mathieu',
  'La Trinité-de-Thouberville',
  'Le Bois-Hellain',
  'Le Bosc-Roger-en-Roumois',
  'Le Landin',
  'Le Torpt',
  'Les Préaux',
  'Lieurey',
  'Manneville-la-Raoult',
  'Manneville-sur-Risle',
  'Marais-Vernier',
  'Martainville',
  'Montfort-sur-Risle',
  'Morainville-Jouveaux',
  'Noards',
  'Pont-Audemer',
  'Pont-Authou',
  'Quillebeuf-sur-Seine',
  'Rougemontiers',
  'Routot',
  'Saint-Aubin-sur-Quillebeuf',
  'Saint-Benoît-des-Ombres',
  'Saint-Christophe-sur-Condé',
  'Saint-Denis-des-Monts',
  'Saint-Étienne-l’Allier',
  'Saint-Georges-du-Mesnil',
  'Saint-Georges-du-Vièvre',
  'Saint-Germain-Village',
  'Saint-Grégoire-du-Vièvre',
  'Saint-Jean-de-la-Léqueraye',
  'Saint-Léger-du-Gennetey',
  'Saint-Maclou',
  'Saint-Mards-de-Blacarville',
  'Saint-Martin-Saint-Firmin',
  'Saint-Ouen-de-Thouberville',
  'Saint-Ouen-des-Champs',
  'Saint-Ouen-du-Tilleul',
  'Saint-Philbert-sur-Boissey',
  'Saint-Philbert-sur-Risle',
  'Saint-Pierre-de-Cormeilles',
  'Saint-Pierre-des-Ifs',
  'Saint-Pierre-du-Val',
  'Saint-Samson-de-la-Roque',
  'Saint-Siméon',
  'Saint-Sulpice-de-Grimbouville',
  'Saint-Sylvestre-de-Cormeilles',
  'Saint-Symphorien',
  'Saint-Thurien',
  'Sainte-Croix-sur-Aizier',
  'Sainte-Opportune-la-Mare',
  'Selles',
  'Theillement',
  'Thierville',
  'Thuit-Hébert',
  'Tocqueville',
  'Tourville-sur-Pont-Audemer',
  'Toutainville',
  'Touville',
  'Triqueville',
  'Trouville-la-Haule',
  'Valletot',
  'Vannecrocq',
  'Vieux-Port',
  'Voiscreville',
].map(normalizeCityName);
